modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "mcarf"
version = "${version}"
displayName = "MCA: Reborn Fantasy Addon"
authors = "'ArtofShannonLee', 'AverageTurtle.' and 'Xaidee'!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.mcarf]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcarf]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcarf]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mcarf]]
modId = "mca"
mandatory = true
versionRange = "[7.5.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mcarf]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.1.40,)"
ordering = "AFTER"
side = "BOTH"